# Generated by Django 4.0.5 on 2022-06-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='sticky',
            field=models.BooleanField(default=False, verbose_name='isSticky?'),
        ),
    ]
